config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users

  resource :playground, controller: 'playground' do
    collection do
      get :demo2
    end
  end

  root 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :following, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :relationships,
    foreign_key: 'user_id'

  has_many :followings,
    through: :relationships,
    source: 'following'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playground_controller.rb
class PlaygroundController < ApplicationController
  def show
  end

  def demo2
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :published, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @users = User.all
  end

  # GET /users/1/edit
  def edit
    @users = User.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    @user.followings += User.where(id: params[:followings]).all
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playground_helper.rb
module PlaygroundHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Twitter">
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'  %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'shared/navbar' %>

<div class="container">
  <div class="page-header">
    <h3>Twitter Copycat</h3>
  </div>

  <%= yield %>
</div>

</body>
</html>

app/views/playground/demo2.html.erb
<div class="row" ng-controller="Demo2Controller">
  <div class="col-md-6">
    <div class="form-group">
      <label class="control-label">
        A:
      </label>

      <input type="text" class="form-control" ng-model="a">
    </div>

    <div class="form-group">
      <label class="control-label">
        B:
      </label>

      <input type="text" class="form-control" ng-model="b">
    </div>

    <div class="form-group">
      <label class="control-label">
        C:
      </label>

      <input type="text" class="form-control" ng-model="c">
    </div>

    <div class="form-group" ng-show="result">
      <label class="control-label">
        Result:
      </label>

      <p class="form-control-static">
        {{ result }}
      </p>
    </div>
  </div>

  <div class="col-md-6">
    <button type="button" class="btn btn-primary" ng-click="plus()">
      Plus
    </button>

    <button type="button" class="btn btn-primary" ng-click="minus()">
      Minus
    </button>

    <button type="button" class="btn btn-primary" ng-click="multiply()">
      Multiply
    </button>

    <button type="button" class="btn btn-primary" ng-click="divide()">
      Divide
    </button>

    <button type="button" class="btn btn-primary" ng-click="mod()">
      Mod
    </button>
  </div>
</div>

app/views/playground/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <label class="control-label">
        A:
      </label>

      <input type="text" class="form-control" id="a">
    </div>

    <div class="form-group">
      <label class="control-label">
        B:
      </label>

      <input type="text" class="form-control" id="b">
    </div>

    <div class="form-group" id="result_wrapper">
      <label class="control-label">
        Result:
      </label>

      <p class="form-control-static" id="result">
        xxx
      </p>
    </div>
  </div>

  <div class="col-md-6">
    <button type="button" data-operator="plus" class="btn btn-primary btn-operator">
      Plus
    </button>

    <button type="button" data-operator="minus" class="btn btn-primary btn-operator">
      Minus
    </button>

    <button type="button" data-operator="multiply" class="btn btn-primary btn-operator">
      Multiply
    </button>

    <button type="button" data-operator="divide" class="btn btn-primary btn-operator">
      Divide
    </button>

    <button type="button" data-operator="mod" class="btn btn-primary btn-operator">
      Mod
    </button>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label "Poster:" %><br>

    <% users = User.all.map {|u| [u.name, u.id] } %>
    <%= select_tag 'post[user_id]', options_for_select(users, @post.user_id) %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.published %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_post_path, class: 'btn btn-default' do %>
  <i class="fa fa-plus"></i>
  New Post
<% end %>

<button type="button" id="test_button1" data-number="1" class="button">
  Click Me 1
</button>

<button type="button" id="test_button2" data-number="2" class="button">
  Click Me 2
</button>

<button type="button" id="test_button3" data-number="3" class="button">
  Click Me 3
</button>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Published:</strong>
  <%= @post.published %>
</p>

<p>
  <strong>Poster:</strong>
  <%= @post.user.name %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Brand</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input class="form-control" placeholder="Search" type="text">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :followings, class: 'control-label' %>

        <select name="followings[]" multiple class="form-control">
          <% @users.each do |user| %>
          <option value="<%= user.id %>"><%= user.name %></option>
          <% end %>
        </select>
      </div>

      <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary">
      </div>
    <% end %>
  <div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p >

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<p>
  followings:
  <% @user.followings.each do |following| %>
    <%= following.name %>
  <% end %>
</p>

<p>
  <strong>Posts:</strong>
  <% @user.posts.each do |post| %>
  <h3>Title:  <%= post.title %></h3>
  <%= post.body %></br>
  Published: <%= post.published %>
  <hr>
  <% end %>
</p>